# Generated by Django 3.2.3 on 2021-08-31 02:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('cwID', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('language', models.CharField(choices=[('C#', 'C#'), ('C++', 'C++'), ('Go', 'Go'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('PHP', 'PHP'), ('Python', 'Python'), ('Ruby', 'Ruby'), ('Rust', 'Rust'), ('Scala', 'Scala'), ('SQL', 'SQL'), ('TypeScript', 'TypeScript')], default='JavaScript', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
                ('tags', models.ManyToManyField(blank=True, to='katas.Tag')),
            ],
        ),
    ]
